words = [
    "LSHIFT",
    "RSHIFT",
    "aeiou",
    "akitas",
    "aoc",
    "clippy",
    "evaluable",
    "fft",
    "joltage",
    "joltages",
    "mkdir",
    "mktemp",
    "nixpkgs",
    "numtide",
    "nuon",
    "nushell",
    "pkgs",
    "robo",
    "rustfmt",
    "stddev",
    "stdenv",
    "svr",
    "treefmt",
    "unspanned",
    "vizslas",
]
