fn_params_layout = "Compressed"
max_width = 230
newline_style = "Unix"
short_array_element_width_threshold = 230
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
